#!/usr/bin/env python3

# Copyright 2022 iiPython

# Modules
import os
import sys
from edos import fs

# Initialization
sys.argv = sys.argv[1:]
if not sys.argv:
    exit("""Usage:
  mkd <path>

Creates a directory assuming the path does not already exist.""")

path = fs.resolve(sys.argv[0])
if os.path.exists(path):
    exit(f"mkd: {fs.clean(path)} already exists")

os.makedirs(path)
