#!/usr/bin/env python3

# Copyright 2022 iiPython

# Modules
import os
import sys
from edos import fs

# Initialization
sys.argv = sys.argv[1:]
if not sys.argv:
    exit("""Usage:
  touch <path>

Creates an empty file with the given name assuming the path does not already exist.""")

path = fs.resolve(sys.argv[0])
if os.path.exists(path):
    exit(f"touch: {fs.clean(path)} already exists")

open(path, "w+").write("")
